#!/usr/bin/env python3
"""
relink_legacy.py — point the hand-written pages at the new routes.

manual.html, enrol.html, signup.html, privacy.html and classes.html predate the
rewire. They keep their own layout (doc.css, a form, a payment flow) and are not
generated by build_pages.py, but their links pointed at anchors on the old
single-page index — #services, #pricing, #how, #contact, #app — every one of
which is now a route of its own. Left alone they would land visitors at the top
of the new home page with nothing highlighted.

Idempotent. Safe to re-run.

    python _layout/relink_legacy.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).parent.parent

PAGES = [
    "manual.html", "enrol.html", "signup.html", "privacy.html",
    "classes.html", "credits.html", "policies.html", "edu.html", "demo.html",
]

# Order matters: the anchored forms must be rewritten before the bare ones,
# or `index.html#pricing` becomes `/#pricing`.
REWRITES = [
    ('href="index.html#services"', 'href="/services"'),
    ('href="index.html#network"', 'href="/network"'),
    ('href="index.html#how"', 'href="/how-it-works"'),
    ('href="index.html#pricing"', 'href="/organisations#pricing"'),
    ('href="index.html#suite"', 'href="/about"'),
    ('href="index.html#contact"', 'href="/about"'),
    ('href="index.html#app"', 'href="/signin"'),
    ('href="index.html"', 'href="/"'),
    ('href="manual.html#', 'href="/manual#'),
    ('href="manual.html"', 'href="/manual"'),
    ('href="privacy.html#', 'href="/privacy#'),
    ('href="privacy.html"', 'href="/privacy"'),
    ('href="/privacy.html"', 'href="/privacy"'),
    ('href="enrol.html#', 'href="/enrol#'),
    ('href="enrol.html"', 'href="/enrol"'),
    ('href="signup.html"', 'href="/signup"'),
    ('href="/classes.html"', 'href="/classes"'),
    ('href="classes.html"', 'href="/classes"'),
]

# The nav each legacy page carries. One nav per page, same destinations as the
# generated pages' TopNav, so a visitor moving between them sees one site.
LEGACY_NAV = """        <nav>
            <a href="/">Home</a>
            <a href="/services">Services</a>
            <a href="/network">Network</a>
            <a href="/organisations">Organisations</a>
            <a href="/manual">Manual</a>
            <a href="/signin">Sign in</a>
            <a href="/request">Start a request</a>
        </nav>"""


def replace_nav(text: str) -> str:
    """Swap the whole <nav>...</nav> inside .topbar for the shared set."""
    start = text.find("<nav>")
    end = text.find("</nav>", start)
    if start == -1 or end == -1:
        return text
    indent_start = text.rfind("\n", 0, start) + 1
    return text[:indent_start] + LEGACY_NAV + "\n" + text[end + len("</nav>"):].lstrip("\n")


def main() -> int:
    touched = []
    for name in PAGES:
        path = ROOT / name
        if not path.is_file():
            continue
        original = path.read_text(encoding="utf-8")
        text = original
        for old, new in REWRITES:
            text = text.replace(old, new)
        if "<div class=\"topbar\">" in text:
            text = replace_nav(text)
        if text != original:
            with open(path, "w", encoding="utf-8", newline="") as fh:
                fh.write(text)
            touched.append(name)

    print("Relinked: " + (", ".join(touched) if touched else "nothing to change"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
